# Generated by Django 4.2 on 2023-04-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_booking_check_in_alter_booking_check_out'),
        ('adminworkenv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
            preserve_default=False,
        ),
    ]
