# Generated by Django 4.2 on 2023-05-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminworkenv', '0003_alter_checkin_check_in_alter_checkin_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
    ]
