# Generated by Django 4.2 on 2023-05-22 19:16

import adminworkenv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminworkenv', '0004_checkin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='created_at',
            field=models.DateField(default=adminworkenv.models.get_date),
        ),
    ]
