# Generated by Django 4.2 on 2023-05-22 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminworkenv', '0006_alter_checkin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
