# Generated by Django 4.2 on 2023-05-22 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminworkenv', '0007_alter_checkin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 5, 22)),
        ),
    ]
