# Generated by Django 4.2 on 2023-04-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
