# Generated by Django 4.2 on 2023-04-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
