# Generated by Django 4.2 on 2023-04-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0013_alter_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=10),
        ),
    ]
