# Generated by Django 4.0.5 on 2023-04-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_user_remove_booking_user_booking_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
