# Generated by Django 4.0.5 on 2023-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_booking_email_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
