# Generated by Django 4.2 on 2023-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_room_id_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(default=2, upload_to='hotel/images/'),
            preserve_default=False,
        ),
    ]
