# Generated by Django 4.2 on 2023-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Стандарт', 'Стандарт'), ('Стандарт+', 'Стандарт+'), ('Люкс', 'Люкс')], max_length=15),
        ),
    ]
