# Generated by Django 4.2 on 2023-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Standard', 'Стандарт'), ('Superior', 'Стандарт+'), ('Deluxe', 'Люкс')], max_length=15),
        ),
    ]
