# Generated by Django 4.2 on 2023-05-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_alter_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='room',
            name='img2',
            field=models.ImageField(default=3, upload_to='hotel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='img3',
            field=models.ImageField(default=6, upload_to='hotel/images/'),
            preserve_default=False,
        ),
    ]
