# Generated by Django 4.2 on 2023-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_rename_img_room_img1_room_img2_room_img3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='img2',
            new_name='img_for_detail1',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='img3',
            new_name='img_for_detail2',
        ),
        migrations.AddField(
            model_name='room',
            name='img_for_detail3',
            field=models.ImageField(default=8, upload_to='hotel/images/'),
            preserve_default=False,
        ),
    ]
